name: Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - name: "Pull docker testnet image"
        run: docker pull ghcr.io/scrtlabs/localsecret:v1.4.0-beta.6
      - name: Install npm dependencies
        run: yarn
      - name: Run tests
        run: yarn test
